version: '3.8'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    build:
      context: ./
      dockerfile: db.Dockerfile
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123456789
    ports:
       - '5430:5432'
    volumes:
       - pgdb:/var/lib/postgresql/data
